import sys

ayuda = sys.argv[1]
ayuda_interfaz = sys.argv[1]


if ayuda == "ayuda" or ayuda == "Ayuda" or ayuda == "help" or ayuda == "Help":
    print("Para ejecutar el programa y la interfaz gráfica, debemos hacer lo siguiente:\n")
    print("Debemos ubicarnos en la carpeta de 'SistemaTransaccionalDeVentas' en nuestro editor de codigo, podemos usar los comandos 'cd (nombre de la carpeta u archivo)' para movernos entre carpetas\n")
    print("Una vez ubicada la carpeta, debemos de escribir lo siguiente: py main.py\n")
    print("Con eso ya estaríamos accediendo al programa y su interfaz")
else:
    print("El comando de ayuda para ejecutar la interfaz es: py ayuda.py ayuda \n \n")
    
if ayuda_interfaz == "Como uso la interfaz" or ayuda_interfaz == "como uso la interfaz":
    print("Para usar la interfaz gráfica, debemos hacer lo siguiente:\n")
    print("En la primera ventana podemos ver la Bienvenida al programa, nos pedirá ingresar un usuario y contraseña que hayamos guardado en nuestra base de datos, dependiendo el usuario que se ingrese tendrá permisos de trabajador o de administrador, el trabajador solo podrá acceder al apartado de las ventas y realizarlas para poder actualizar la base de datos, mientras que el administrador podrá agregar nuevos usuarios, productos y ventas a la base de datos, incluyendo la posibilidad de ver la información de cada una de las ventas realizadas en una ventana especial.\n")
    print("Eso sería todo del apartado de ventas. \n \n")
    print("Si tu usuario es trabajador, te dirigirá al apartado de ventas donde se encontrarán todas las ventas que se hagan en la tienda. En la parte superior podemos encontrar la Bienvenida al usuario, la hora y fecha de ese mismo día, esa información le será útil al usuario con rol de administrador pero lo explicaremos más adelante. Bien, en esta ventana se pueden ingresar productos para la venta por su nombre o código, por medio de unos inputs abajo de la bienvenida, fecha y hora.\n \nUna vez agregado el producto al carrito podemos seleccionarlo dando click encima de este y una vez hecho eso podemos hacer lo siguiente:\n \n 1. Podemos hacer un pago por esa venta dandole a 'Pagar'\n \n 1.1 Una vez le dimos a pagar, nos mostrará una ventana donde nos dará el total de la compra y un espacio para agregar el dinero necesaio para hacer la venta, si el dinero ingresado es menor al total, entonces no se hará la venta porque faltaría dinero para completarla, si tenemos el dinero suficiente nos mostrará el cambio que le devolvemos a la persona que hizo la compra, una vez hecho lo anterior, le damos a 'Aceptar' y con eso ya tendríamos la venta hecha, pero se nos desabilitarán los campos para ingresar los productos al carrito, esto para tener un mejor orden con cada venta a realizar y no tener conflicto con las bases de datos.\n \n 1.2 Si queremos realizar una nueva compra por parte de la persona, tendremos que darle al botón 'Nueva Compra' y se nos habilitarán los campos para ingresar productos al carrito nuevamente.\n \n2. Anular la venta con el botón de 'Anular venta'\n \n3. Modificar la cantidad del producto dandole en 'Cambiar Cantidad', luego nos va a mostrar una ventana para poder modificar la cantidad del producto que seleccionamos, una vez ingresada la nueva cantidad le damos a 'Aceptar' y se mostrará la nueva cantidad del producto.\n")
    print("Si tu usuario es administrador, entonces tendrás acceso al control de ventas, productos y usuarios, para dirigirnos a cada una de estas pantallas, le podemos dar al botón que dice 'Cambiar Vista' eso nos desplegará un menú con la dirección hacia cada una de las pantallas antes mencionadas.\n \n")
    print("En la pantalla de productos podemos hacer lo siquiente: \n \n1. Agregar un producto. \n \n2. Modificar un producto. \n \n3. Eliminar un producto. \n \n")
    print("En la pantalla de usuarios podemos hacer lo siguiente: \n \n 1. Agregar un nuevo usuario de tipo trabajador o administrador. \n \n2. Modificar un usuario. \n \n3. Eliminar un usuario.\n \n")
    print("Y por último tenemos el apartado del reporte de ventas, podemos generarlo de dos formas: la primera es dando click al botón que dice 'Hoy' y eso nos mostrará las ventas que se hicieron en la fecha actual, la segunda es hacerlo indicándole una fecha en específico, o bien, un rango determinado de fechas que nos muestren las ventas que se hicieron en ese tiempo. \n \n")
    print("La información que se mostrará al momento de darle a alguno de esos botones será: el nombre del usuario, la cantidad de productos vendidos, el total de la venta, la fecha y hora en la que se realizo la venta. Y si queremos más información sobre alguna venta, solo la seleccionamos y le damos al botón de 'Mas Info' y nos indicará el código del producto, nombre del producto, su cantidad, su precio unitario y el total. \n \n")
    print("Si queremos guardar ese reporte de ventas en una archivo de .csv, simplemente le damos al botón 'Guardar CSV' y con eso creará un archivo de excel que se almacenará en una carpeta llamada 'ventas_csv', aparte, al momento de darle al botón, se le indicarán las instrucciones a seguir para poder mandar un archivo por correo desde python. \n \n")
    print("Aclaraciones: No podemos reportar una venta si esta no existe dentro de la base de datos, no podemos asignar la cantidad o precio de un producto con letras o cualquier otro tipo de dato que no sea un número, lo mismo aplica a la hora de pagarlo, otra cosa por aclarar, si en la base de datos no existe una tabla o alguna columna, podemos crearla al momento de agregar un producto, usuario o venta, y si nos aparece un error de tabla no encontrada en la consola, simplemente cerramos la interfaz y la volvemos a ejecutar normalmente y ya se comenzarán a guardar los cambios a partir de ese momento. \n \n")